/**
 * BuildService — bundles the browser application with esbuild and prepares `public/`.
 *
 * Real, verifiable steps:
 *  1. `public/build/app.js` + `app.css` are produced by esbuild from `src/renderer/main.js`;
 *  2. large WASM packages (`@luau-rs/luau`, `wasmoon`) are kept *external* and copied into
 *     `public/vendor/`, then wired through an import map so the browser loads the real
 *     WebAssembly runtimes instead of a bundled stub;
 *  3. hashes are computed for cache busting, and the HTML is generated with the correct
 *     asset URLs.
 *
 * If the build fails the previous artifacts stay on disk and the error is reported with
 * the real esbuild diagnostics (file, line, column), never swallowed.
 */

import fsp from 'node:fs/promises';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { ErrorKind } from '../shared/constants.js';
import { AppError, toAppError } from '../shared/errors.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const PROJECT_ROOT = path.resolve(HERE, '..', '..');

/** Vendor packages that must stay as real ES modules in the browser. */
const VENDOR_PACKAGES = [
  {
    specifier: '@luau-rs/luau/worker',
    packagePath: '@luau-rs/luau',
    distDir: 'dist',
    entryFile: 'worker-api.js',
    shim: 'luau-rs/worker.js',
    extraEntries: ['worker-server-BdoVr0x2.js', 'worker-server-CFjb6otN.js', 'worker-wasm-Bc9IP5xV.js', 'worker-protocol-CDOAT_ZN.js'],
  },
  {
    specifier: '@luau-rs/luau/analysis/worker',
    packagePath: '@luau-rs/luau',
    distDir: 'dist',
    entryFile: 'analysis-worker-browser.js',
    shim: 'luau-rs/analysis-worker.js',
  },
];

/**
 * Binary assets copied verbatim into `public/vendor/` (they are not ES modules: the runtime
 * fetches them by URL). `wasmoon` is bundled by esbuild — its `dist/index.js` is a UMD file,
 * so it cannot be re-exported as a module; the WASM payload stays a real file on disk.
 */
const VENDOR_ASSETS = [
  { packagePath: 'wasmoon', distDir: 'dist', file: 'glue.wasm', target: 'vendor/wasmoon/glue.wasm' },
];

/**
 * Node built-ins referenced by `wasmoon`'s universal bundle in branches that are unreachable
 * in the browser. Aliasing them to a stub keeps the browser bundle free of `node:*` imports.
 */
const BROWSER_ALIASES = {
  url: null,
  module: null,
};

/** Extra entry points built next to `app.js` (real worker bundles). */
const EXTRA_ENTRY_POINTS = [
  { entry: 'runtime/workers/lua54.worker.js', output: 'lua54.worker.js' },
];

export class BuildService {
  #builtAt = null;
  #lastError = null;
  #stats = null;

  constructor({ logger, errorHandler, projectRoot = PROJECT_ROOT, publicDir = null }) {
    this.logger = logger;
    this.errorHandler = errorHandler;
    this.projectRoot = projectRoot;
    this.publicDir = publicDir ?? path.join(projectRoot, 'public');
    this.rendererDir = path.join(projectRoot, 'src', 'renderer');
  }

  get vendorDir() {
    return path.join(this.publicDir, 'vendor');
  }

  get buildDir() {
    return path.join(this.publicDir, 'build');
  }

  get lastError() {
    return this.#lastError;
  }

  get builtAt() {
    return this.#builtAt;
  }

  /**
   * Runs the full build.
   * @param {{ minify?: boolean, sourcemap?: boolean, watch?: boolean }} [options]
   */
  async build({ minify = true, sourcemap = true, watch = false } = {}) {
    const started = Date.now();
    try {
      const esbuild = await import('esbuild');
      await fsp.mkdir(this.buildDir, { recursive: true });
      await fsp.mkdir(this.vendorDir, { recursive: true });

      const externals = [...VENDOR_PACKAGES.map((entry) => entry.specifier), 'node:*'];
      const shared = {
        bundle: true,
        format: 'esm',
        target: ['chrome110', 'firefox110', 'safari16', 'edge110'],
        external: externals,
        minify,
        sourcemap: sourcemap ? 'linked' : false,
        legalComments: 'none',
        logLevel: 'silent',
        metafile: true,
        loader: { '.css': 'css', '.svg': 'dataurl', '.woff2': 'file' },
        alias: this.#browserAliases(),
        define: {
          'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV ?? 'production'),
          __LUMEN_BUILD__: JSON.stringify(new Date().toISOString()),
        },
      };

      const result = await esbuild.build({
        ...shared,
        entryPoints: [path.join(this.rendererDir, 'main.js')],
        outfile: path.join(this.buildDir, 'app.js'),
        banner: { js: '/* Lumen Studio — renderer bundle. Generated by BuildService (esbuild). */' },
      });

      // Worker bundles: separate entry points, same externals and same loader rules.
      const extra = [];
      for (const entryPoint of EXTRA_ENTRY_POINTS) {
        const outcome = await esbuild.build({
          ...shared,
          entryPoints: [path.join(this.rendererDir, entryPoint.entry)],
          outfile: path.join(this.buildDir, entryPoint.output),
        });
        extra.push({ file: entryPoint.output, metafile: outcome.metafile });
      }

      // esbuild writes CSS next to the JS when the entry imports it.
      await this.#renameCssOutput(path.join(this.buildDir, 'app.css'));
      await this.#prepareVendor();
      const entryHtml = await this.#writeIndexHtml();
      const sizes = await this.#measureArtifacts();

      this.#builtAt = Date.now();
      this.#lastError = null;
      this.#stats = {
        durationMs: Date.now() - started,
        outputs: Object.entries(result.metafile?.outputs ?? {}).map(([file, info]) => ({
          file: path.relative(this.projectRoot, path.resolve(this.projectRoot, file)),
          bytes: info.bytes,
        })),
        sizes,
        warnings: (result.warnings ?? []).map((warning) => ({
          text: warning.text,
          file: warning.location?.file ?? null,
          line: warning.location?.line ?? null,
        })),
        extraEntries: extra.map((entry) => entry.file),
      };
      this.logger.success(`Interfaz compilada en ${this.#stats.durationMs} ms (${sizes.js.formatted} JS, ${sizes.css.formatted} CSS)`, {
        source: 'BuildService',
      });
      return { ok: true, ...this.#stats, html: entryHtml, builtAt: this.#builtAt };
    } catch (err) {
      const appError = this.#describeBuildError(err);
      this.#lastError = appError.toJSON();
      this.errorHandler.report(appError, { source: 'BuildService.build' });
      return { ok: false, error: appError, diagnostics: appError.detail?.diagnostics ?? null };
    }
  }

  /** esbuild errors carry structured positions: keep them for the UI. */
  #describeBuildError(err) {
    const diagnostics = Array.isArray(err?.errors)
      ? err.errors.map((entry) => ({
        text: entry.text,
        file: entry.location?.file ? path.relative(this.projectRoot, entry.location.file) : null,
        line: entry.location?.line ?? null,
        column: entry.location?.column ?? null,
        lineText: entry.location?.lineText ?? null,
      }))
      : null;
    return toAppError(err, {
      kind: ErrorKind.UI,
      code: 'E_BUILD_FAILED',
      message: 'La compilación de la interfaz falló',
      detail: { diagnostics, hint: 'Revisa los archivos indicados y vuelve a ejecutar `npm run build`.' },
    });
  }

  /** Absolute paths for the Node-builtin aliases (esbuild requires resolved paths). */
  #browserAliases() {
    const stub = path.join(this.projectRoot, 'src', 'renderer', 'runtime', 'shims', 'node-builtins.js');
    return Object.fromEntries(Object.keys(BROWSER_ALIASES).map((specifier) => [specifier, stub]));
  }

  async #renameCssOutput(target) {
    const candidates = [
      path.join(this.buildDir, 'app.css'),
      path.join(this.buildDir, 'main.css'),
      path.join(this.buildDir, 'app.js.css'),
    ];
    for (const candidate of candidates) {
      if (candidate === target) {
        if (await exists(candidate)) return;
        continue;
      }
      if (await exists(candidate)) {
        await fsp.rename(candidate, target);
        return;
      }
    }
  }

  /**
   * Copies the real WASM packages into `public/vendor/` and generates the import map.
   * The upstream packages are used verbatim (no patching), so the WebAssembly binaries and
   * their worker entry points stay byte-identical to what npm published.
   */
  async #prepareVendor() {
    const copied = [];
    for (const entry of VENDOR_PACKAGES) {
      const packageDir = path.join(this.projectRoot, 'node_modules', entry.packagePath, entry.distDir);
      const stat = await fsp.stat(packageDir).catch(() => null);
      if (!stat?.isDirectory()) {
        throw new AppError({
          message: `No se encontró el paquete ${entry.packagePath} en node_modules (falta ejecutar "npm install")`,
          code: 'E_DEPENDENCY_MISSING',
          kind: ErrorKind.UI,
          detail: { packagePath: entry.packagePath, expectedAt: packageDir },
        });
      }
      const targetDir = path.join(this.vendorDir, entry.packagePath.replace('@', '').replace('/', '-'));
      await fsp.mkdir(targetDir, { recursive: true });
      // Copy the whole dist directory: the packages rely on relative chunk/file references.
      await fsp.cp(packageDir, targetDir, { recursive: true, force: true });
      const shimPath = path.join(this.vendorDir, entry.shim);
      await fsp.mkdir(path.dirname(shimPath), { recursive: true });
      const relative = path.relative(path.dirname(shimPath), path.join(targetDir, entry.entryFile)).split(path.sep).join('/');
      await fsp.writeFile(shimPath, `// Generated by BuildService: re-export of the real package entry point.\nexport * from './${relative}';\n`, 'utf8');
      const wasmFiles = (await fsp.readdir(targetDir)).filter((file) => file.endsWith('.wasm'));
      copied.push({
        specifier: entry.specifier,
        shim: path.relative(this.publicDir, shimPath).split(path.sep).join('/'),
        target: path.relative(this.publicDir, targetDir).split(path.sep).join('/'),
        wasm: wasmFiles,
        entry: entry.entryFile,
      });
    }
    for (const asset of VENDOR_ASSETS) {
      const source = path.join(this.projectRoot, 'node_modules', asset.packagePath, asset.distDir, asset.file);
      const stat = await fsp.stat(source).catch(() => null);
      if (!stat?.isFile()) {
        throw new AppError({
          message: `No se encontró el binario ${asset.file} de ${asset.packagePath} en node_modules`,
          code: 'E_DEPENDENCY_MISSING',
          kind: ErrorKind.UI,
          detail: { expectedAt: source },
        });
      }
      const destination = path.join(this.publicDir, asset.target);
      await fsp.mkdir(path.dirname(destination), { recursive: true });
      await fsp.copyFile(source, destination);
      copied.push({ specifier: null, asset: asset.file, target: path.relative(this.publicDir, destination).split(path.sep).join('/'), bytes: stat.size });
    }
    this.#vendorManifest = copied;
    return copied;
  }

  get vendorManifest() {
    return this.#vendorManifest ?? [];
  }

  #vendorManifest = [];

  async #writeIndexHtml() {
    const templatePath = path.join(this.rendererDir, 'index.html');
    const template = await fsp.readFile(templatePath, 'utf8');
    const jsHash = await shortHash(path.join(this.buildDir, 'app.js'));
    const cssHash = await shortHash(path.join(this.buildDir, 'app.css'));
    const importMap = {
      imports: Object.fromEntries(
        this.vendorManifest
          .filter((entry) => typeof entry.specifier === 'string' && entry.specifier !== '' && typeof entry.shim === 'string')
          .map((entry) => [entry.specifier, `./${entry.shim}`]),
      ),
    };
    const html = template
      .replace('/*__LUMEN_IMPORT_MAP__*/', JSON.stringify(importMap, null, 2))
      .replace('__LUMEN_JS__', `./build/app.js?v=${jsHash}`)
      .replace('__LUMEN_CSS__', `./build/app.css?v=${cssHash}`);
    const outPath = path.join(this.publicDir, 'index.html');
    await fsp.writeFile(outPath, html, 'utf8');
    return outPath;
  }

  async #measureArtifacts() {
    const measure = async (file) => {
      const stat = await fsp.stat(file).catch(() => null);
      return { bytes: stat?.size ?? 0, formatted: formatBytes(stat?.size ?? 0) };
    };
    const js = await measure(path.join(this.buildDir, 'app.js'));
    const css = await measure(path.join(this.buildDir, 'app.css'));
    const workers = {};
    for (const entryPoint of EXTRA_ENTRY_POINTS) {
      workers[entryPoint.output] = await measure(path.join(this.buildDir, entryPoint.output));
    }
    let vendorBytes = 0;
    for (const entry of this.vendorManifest) {
      if (Number.isFinite(entry.bytes)) {
        vendorBytes += entry.bytes;
        continue;
      }
      const dir = path.join(this.publicDir, entry.target);
      vendorBytes += await directorySize(dir);
    }
    return { js, css, workers, vendor: { bytes: vendorBytes, formatted: formatBytes(vendorBytes) } };
  }

  /** Verifies that the artifacts on disk are present and non-empty. */
  async verify() {
    const checks = [
      { name: 'index.html', path: path.join(this.publicDir, 'index.html') },
      { name: 'build/app.js', path: path.join(this.buildDir, 'app.js') },
      { name: 'build/app.css', path: path.join(this.buildDir, 'app.css') },
      ...EXTRA_ENTRY_POINTS.map((entryPoint) => ({ name: `build/${entryPoint.output}`, path: path.join(this.buildDir, entryPoint.output) })),
      ...this.vendorManifest.map((entry) => ({
        name: entry.shim ?? entry.target,
        path: path.join(this.publicDir, entry.shim ?? entry.target),
      })),
    ];
    const results = [];
    for (const check of checks) {
      const stat = await fsp.stat(check.path).catch(() => null);
      results.push({ name: check.name, exists: stat !== null, bytes: stat?.size ?? 0, ok: Boolean(stat && stat.size > 0) });
    }
    return { ok: results.every((entry) => entry.ok), results, builtAt: this.#builtAt };
  }

  /** Rebuilds when any renderer source is newer than the last build. */
  needsRebuild() {
    if (!this.#builtAt) return true;
    const newest = newestMtime(this.rendererDir);
    return newest > this.#builtAt;
  }

  stats() {
    return { builtAt: this.#builtAt, error: this.#lastError, ...(this.#stats ?? {}) };
  }

  /**
   * Optional esbuild watch mode (used by `npm run dev`).
   * Returns a disposer.
   */
  async watch() {
    const esbuild = await import('esbuild');
    const shared = {
      bundle: true,
      format: 'esm',
      target: ['chrome110', 'firefox110', 'safari16'],
      external: [...VENDOR_PACKAGES.map((entry) => entry.specifier), 'node:*'],
      minify: false,
      sourcemap: 'linked',
      logLevel: 'silent',
      loader: { '.css': 'css' },
      alias: this.#browserAliases(),
      define: {
        'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV ?? 'development'),
        __LUMEN_BUILD__: JSON.stringify(new Date().toISOString()),
      },
    };

    let lastPrepare = 0;
    const prepare = async () => {
      // Two contexts rebuild independently; vendor/HTML preparation runs once per burst.
      if (Date.now() - lastPrepare < 250) return;
      lastPrepare = Date.now();
      await this.#renameCssOutput(path.join(this.buildDir, 'app.css'));
      await this.#prepareVendor();
      await this.#writeIndexHtml();
      this.#builtAt = Date.now();
      this.logger.success('Interfaz recompilada (watch)', { source: 'BuildService' });
    };

    const hook = {
      name: 'lumen-rebuild-hook',
      setup: (build) => {
        build.onEnd(async (result) => {
          if (result.errors.length > 0) {
            this.#lastError = this.#describeBuildError({ errors: result.errors }).toJSON();
            this.logger.error(`Recompilación fallida: ${this.#lastError.message}`, { source: 'BuildService' });
            return;
          }
          await prepare();
        });
      },
    };

    const contexts = [];
    contexts.push(await esbuild.context({
      ...shared,
      entryPoints: [path.join(this.rendererDir, 'main.js')],
      outfile: path.join(this.buildDir, 'app.js'),
      plugins: [hook],
    }));
    for (const entryPoint of EXTRA_ENTRY_POINTS) {
      contexts.push(await esbuild.context({
        ...shared,
        entryPoints: [path.join(this.rendererDir, entryPoint.entry)],
        outfile: path.join(this.buildDir, entryPoint.output),
        plugins: [hook],
      }));
    }

    for (const context of contexts) await context.watch();
    await this.#prepareVendor();
    await this.#writeIndexHtml();
    this.#builtAt = Date.now();
    const state = { closed: false };
    return {
      close: async () => {
        if (state.closed) return;
        state.closed = true;
        for (const context of contexts) await context.dispose();
      },
    };
  }
}

async function exists(file) {
  try {
    await fsp.access(file, fs.constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

async function shortHash(file) {
  try {
    const content = await fsp.readFile(file);
    return crypto.createHash('sha1').update(content).digest('hex').slice(0, 8);
  } catch {
    return 'dev';
  }
}

async function directorySize(dir, depth = 0) {
  if (depth > 3) return 0;
  let total = 0;
  const entries = await fsp.readdir(dir, { withFileTypes: true }).catch(() => []);
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) total += await directorySize(full, depth + 1);
    else {
      const stat = await fsp.stat(full).catch(() => null);
      total += stat?.size ?? 0;
    }
  }
  return total;
}

function newestMtime(dir, depth = 0) {
  if (depth > 4) return 0;
  let newest = 0;
  let entries = [];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return 0;
  }
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) newest = Math.max(newest, newestMtime(full, depth + 1));
    else {
      try {
        newest = Math.max(newest, fs.statSync(full).mtimeMs);
      } catch {
        /* ignore */
      }
    }
  }
  return newest;
}

export function formatBytes(bytes) {
  if (!Number.isFinite(bytes)) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  let value = bytes;
  let index = 0;
  while (value >= 1024 && index < units.length - 1) {
    value /= 1024;
    index += 1;
  }
  return `${value.toFixed(value >= 10 || index === 0 ? 0 : 1)} ${units[index]}`;
}
