/**
 * Command catalogue — every action the application can perform, registered once.
 *
 * The palette (Ctrl+Shift+P), the shortcut manager and the menus all resolve to these ids, so
 * there is a single implementation per action. Commands that cannot run report *why* through
 * `disabledReason` instead of failing silently.
 */

export function registerAppCommands({ commands, app }) {
  const editor = () => app.editor;
  const hasTab = () => (app.tabs?.count ?? 0) > 0;
  const hasSavedTab = () => app.tabs?.activeTab?.saved === true;
  const isRunning = () => app.runtime?.isRunning === true;

  const definitions = [
    /* ----------------------------- Execution ----------------------------- */
    {
      id: 'runtime.run',
      title: 'Ejecutar script',
      category: 'Ejecución',
      icon: 'play',
      keywords: ['run', 'ejecutar', 'lanzar'],
      order: 10,
      run: () => app.runActive(),
      disabledReason: () => (hasTab() ? null : 'No hay ningún archivo abierto'),
    },
    {
      id: 'runtime.runInServer',
      title: 'Ejecutar en el servidor',
      category: 'Ejecución',
      icon: 'cpu',
      keywords: ['server', 'servidor', 'motor'],
      order: 12,
      run: () => app.runActive({ server: true }),
      disabledReason: () => (hasTab() ? null : 'No hay ningún archivo abierto'),
    },
    {
      id: 'runtime.stop',
      title: 'Detener ejecución',
      category: 'Ejecución',
      icon: 'stop',
      keywords: ['stop', 'cancelar', 'detener'],
      order: 14,
      run: () => app.stopExecution(),
      enabled: () => isRunning(),
      disabledReason: () => 'No hay ninguna ejecución en curso',
    },

    /* ------------------------------- Files -------------------------------- */
    {
      id: 'file.new',
      title: 'Nuevo script',
      category: 'Archivo',
      icon: 'plus',
      keywords: ['nuevo', 'crear', 'new'],
      order: 20,
      run: () => app.newScript(),
    },
    {
      id: 'file.open',
      title: 'Abrir script…',
      category: 'Archivo',
      icon: 'folder',
      keywords: ['abrir', 'open'],
      order: 21,
      run: () => app.openPicker(),
    },
    {
      id: 'file.save',
      title: 'Guardar',
      category: 'Archivo',
      icon: 'save',
      keywords: ['guardar', 'save'],
      order: 22,
      run: () => app.saveActive(),
      disabledReason: () => (hasTab() ? null : 'No hay ningún archivo abierto'),
    },
    {
      id: 'file.saveAs',
      title: 'Guardar como…',
      category: 'Archivo',
      icon: 'export',
      keywords: ['guardar como', 'save as', 'copia'],
      order: 23,
      run: () => app.saveActive({ as: true }),
      disabledReason: () => (hasTab() ? null : 'No hay ningún archivo abierto'),
    },
    {
      id: 'file.closeTab',
      title: 'Cerrar pestaña',
      category: 'Archivo',
      icon: 'close',
      keywords: ['cerrar', 'close'],
      order: 24,
      run: () => app.closeActiveTab(),
      disabledReason: () => (hasTab() ? null : 'No hay ninguna pestaña abierta'),
    },
    {
      id: 'file.closeAllTabs',
      title: 'Cerrar todas las pestañas',
      category: 'Archivo',
      keywords: ['cerrar todas'],
      order: 25,
      run: () => app.tabs.closeAll(),
      enabled: () => (app.tabs?.count ?? 0) > 1,
      disabledReason: () => 'Solo hay una pestaña abierta',
    },
    {
      id: 'file.import',
      title: 'Importar script…',
      category: 'Archivo',
      icon: 'upload',
      keywords: ['importar', 'import', 'subir'],
      order: 26,
      run: () => app.importScript(),
    },
    {
      id: 'file.export',
      title: 'Exportar script',
      category: 'Archivo',
      icon: 'download',
      keywords: ['exportar', 'export', 'descargar'],
      order: 27,
      run: () => app.exportActive(),
      enabled: () => hasSavedTab(),
      disabledReason: () => (hasTab() ? 'El archivo todavía no está guardado' : 'No hay ningún archivo abierto'),
    },
    {
      id: 'file.rename',
      title: 'Renombrar script…',
      category: 'Archivo',
      icon: 'edit',
      keywords: ['renombrar', 'rename'],
      order: 28,
      run: () => app.tabs.rename(),
      enabled: () => hasSavedTab(),
      disabledReason: () => 'El archivo todavía no está guardado',
    },
    {
      id: 'file.duplicate',
      title: 'Duplicar script',
      category: 'Archivo',
      icon: 'copy',
      keywords: ['duplicar'],
      order: 29,
      run: () => app.tabs.duplicate(),
      enabled: () => hasSavedTab(),
      disabledReason: () => 'El archivo todavía no está guardado',
    },

    /* ------------------------------ Editor -------------------------------- */
    {
      id: 'editor.format',
      title: 'Formatear documento',
      category: 'Editor',
      icon: 'format',
      keywords: ['formatear', 'format', 'indentar'],
      order: 30,
      run: () => app.formatDocument(),
      disabledReason: () => (hasTab() ? null : 'No hay ningún archivo abierto'),
    },
    {
      id: 'editor.find',
      title: 'Buscar',
      category: 'Editor',
      icon: 'search',
      keywords: ['buscar', 'find'],
      order: 31,
      run: () => editor()?.openFind(),
    },
    {
      id: 'editor.replace',
      title: 'Buscar y reemplazar',
      category: 'Editor',
      icon: 'replace',
      keywords: ['reemplazar', 'replace'],
      order: 32,
      run: () => editor()?.openReplace(),
    },
    {
      id: 'editor.findNext',
      title: 'Buscar siguiente',
      category: 'Editor',
      keywords: ['siguiente'],
      order: 33,
      run: () => editor()?.findNext(),
    },
    {
      id: 'editor.findPrevious',
      title: 'Buscar anterior',
      category: 'Editor',
      keywords: ['anterior'],
      order: 34,
      run: () => editor()?.findPrevious(),
    },
    {
      id: 'editor.gotoLine',
      title: 'Ir a la línea…',
      category: 'Editor',
      icon: 'link',
      keywords: ['linea', 'ir', 'goto'],
      order: 35,
      run: () => app.gotoLine(),
    },
    {
      id: 'editor.searchProject',
      title: 'Buscar en todos los scripts…',
      category: 'Editor',
      icon: 'search',
      keywords: ['proyecto', 'global'],
      order: 36,
      run: () => app.searchProject(),
    },
    {
      id: 'editor.analyzeNow',
      title: 'Analizar ahora',
      category: 'Editor',
      icon: 'check',
      keywords: ['analizar', 'lint', 'diagnóstico'],
      order: 37,
      run: () => app.analyzeNow(),
      disabledReason: () => (hasTab() ? null : 'No hay ningún archivo abierto'),
    },
    {
      id: 'editor.typeAnnotation',
      title: 'Anotar tipos en una copia',
      category: 'Editor',
      icon: 'wand',
      keywords: ['tipos', 'anotaciones'],
      order: 38,
      run: () => app.annotateTypes(),
      disabledReason: () => (hasTab() ? null : 'No hay ningún archivo abierto'),
    },
    {
      id: 'editor.toggleComment',
      title: 'Comentar / descomentar',
      category: 'Editor',
      keywords: ['comentar'],
      order: 39,
      run: () => editor()?.toggleComment(),
    },
    {
      id: 'editor.duplicateLine',
      title: 'Duplicar línea',
      category: 'Editor',
      keywords: ['duplicar linea'],
      order: 40,
      run: () => editor()?.duplicateLine(),
    },
    {
      id: 'editor.deleteLine',
      title: 'Eliminar línea',
      category: 'Editor',
      keywords: ['borrar linea'],
      order: 41,
      run: () => editor()?.deleteLine(),
    },
    {
      id: 'editor.moveLineUp',
      title: 'Mover línea arriba',
      category: 'Editor',
      order: 42,
      run: () => editor()?.moveLineUp(),
    },
    {
      id: 'editor.moveLineDown',
      title: 'Mover línea abajo',
      category: 'Editor',
      order: 43,
      run: () => editor()?.moveLineDown(),
    },
    {
      id: 'editor.selectAll',
      title: 'Seleccionar todo',
      category: 'Editor',
      order: 44,
      run: () => editor()?.selectAll(),
    },
    {
      id: 'editor.addCursorAbove',
      title: 'Añadir cursor arriba',
      category: 'Editor',
      keywords: ['multicursor'],
      order: 45,
      run: () => editor()?.addCursorAbove(),
    },
    {
      id: 'editor.addCursorBelow',
      title: 'Añadir cursor abajo',
      category: 'Editor',
      keywords: ['multicursor'],
      order: 46,
      run: () => editor()?.addCursorBelow(),
    },
    {
      id: 'editor.selectNextOccurrence',
      title: 'Seleccionar la siguiente coincidencia',
      category: 'Editor',
      order: 47,
      run: () => editor()?.selectNextOccurrence(),
    },
    {
      id: 'editor.foldAll',
      title: 'Plegar todo',
      category: 'Editor',
      order: 48,
      run: () => editor()?.foldAll(),
    },
    {
      id: 'editor.unfoldAll',
      title: 'Desplegar todo',
      category: 'Editor',
      order: 49,
      run: () => editor()?.unfoldAll(),
    },
    {
      id: 'editor.undo',
      title: 'Deshacer',
      category: 'Editor',
      order: 50,
      run: () => editor()?.undo(),
    },
    {
      id: 'editor.redo',
      title: 'Rehacer',
      category: 'Editor',
      order: 51,
      run: () => editor()?.redo(),
    },
    {
      id: 'editor.wordWrap',
      title: 'Alternar ajuste de línea',
      category: 'Editor',
      order: 52,
      run: () => app.toggleSetting('editor.wordWrap'),
    },
    {
      id: 'editor.minimap',
      title: 'Alternar minimapa',
      category: 'Editor',
      order: 53,
      run: () => app.toggleSetting('editor.minimap'),
    },
    {
      id: 'editor.zoomIn',
      title: 'Aumentar el tamaño del texto',
      category: 'Editor',
      order: 54,
      run: () => editor()?.zoomIn(),
    },
    {
      id: 'editor.zoomOut',
      title: 'Reducir el tamaño del texto',
      category: 'Editor',
      order: 55,
      run: () => editor()?.zoomOut(),
    },
    {
      id: 'editor.zoomReset',
      title: 'Restablecer el tamaño del texto',
      category: 'Editor',
      order: 56,
      run: () => editor()?.zoomReset(),
    },

    /* ------------------------------- Pestañas ----------------------------- */
    {
      id: 'tabs.next',
      title: 'Siguiente pestaña',
      category: 'Pestañas',
      order: 60,
      run: () => app.tabs?.nextTab(1),
    },
    {
      id: 'tabs.previous',
      title: 'Pestaña anterior',
      category: 'Pestañas',
      order: 61,
      run: () => app.tabs?.nextTab(-1),
    },
    {
      id: 'tabs.switchDialect',
      title: 'Cambiar dialecto del archivo',
      category: 'Pestañas',
      icon: 'layers',
      keywords: ['luau', 'lua', 'dialecto'],
      order: 62,
      run: () => app.tabs?.cycleDialect(),
      enabled: () => hasSavedTab(),
      disabledReason: () => 'El archivo todavía no está guardado',
    },

    /* ------------------------------- Consola ------------------------------ */
    {
      id: 'console.clear',
      title: 'Limpiar la consola',
      category: 'Consola',
      icon: 'trash',
      keywords: ['limpiar', 'clear'],
      order: 70,
      run: () => {
        const result = app.console.clear();
        app.notifications.info(`Consola vaciada (${result.cleared} entradas)`);
      },
    },
    {
      id: 'console.export',
      title: 'Exportar el registro de la consola',
      category: 'Consola',
      icon: 'download',
      keywords: ['exportar', 'log'],
      order: 71,
      run: () => app.exportConsole(),
    },
    {
      id: 'console.copy',
      title: 'Copiar la consola al portapapeles',
      category: 'Consola',
      icon: 'copy',
      order: 72,
      run: () => app.copyConsole(),
    },
    {
      id: 'console.togglePause',
      title: 'Pausar / reanudar la consola',
      category: 'Consola',
      order: 73,
      run: () => app.console.togglePause(),
    },
    {
      id: 'console.showErrors',
      title: 'Ver solo los errores',
      category: 'Consola',
      order: 74,
      run: () => app.focusConsole('ERROR'),
    },

    /* ------------------------------ Navegación ---------------------------- */
    {
      id: 'view.dashboard',
      title: 'Ir al panel',
      category: 'Vista',
      icon: 'dashboard',
      order: 80,
      run: () => app.switchView('dashboard'),
    },
    {
      id: 'view.editor',
      title: 'Ir al editor',
      category: 'Vista',
      icon: 'editor',
      order: 81,
      run: () => app.switchView('editor'),
    },
    {
      id: 'view.scripts',
      title: 'Ir a scripts',
      category: 'Vista',
      icon: 'scripts',
      order: 82,
      run: () => app.switchView('scripts'),
    },
    {
      id: 'view.console',
      title: 'Ir a la consola',
      category: 'Vista',
      icon: 'console',
      order: 83,
      run: () => app.switchView('console'),
    },
    {
      id: 'view.plugins',
      title: 'Ir a plugins',
      category: 'Vista',
      icon: 'plugins',
      order: 84,
      run: () => app.switchView('plugins'),
    },
    {
      id: 'view.settings',
      title: 'Abrir ajustes',
      category: 'Vista',
      icon: 'settings',
      order: 85,
      run: () => app.switchView('settings'),
    },
    {
      id: 'view.about',
      title: 'Acerca de Lumen Studio',
      category: 'Vista',
      icon: 'info',
      order: 86,
      run: () => app.switchView('about'),
    },
    {
      id: 'view.commandPalette',
      title: 'Paleta de comandos',
      category: 'Vista',
      icon: 'wand',
      keywords: ['paleta', 'commands'],
      order: 87,
      run: () => app.palette.show(),
    },
    {
      id: 'view.toggleSidebar',
      title: 'Alternar barra lateral',
      category: 'Vista',
      icon: 'layers',
      keywords: ['sidebar', 'barra'],
      order: 88,
      run: () => app.toggleSidebar(),
    },
    {
      id: 'view.fullscreen',
      title: 'Alternar pantalla completa',
      category: 'Vista',
      icon: 'monitor',
      order: 89,
      run: () => app.toggleFullscreen(),
    },

    /* ------------------------------- Apariencia --------------------------- */
    {
      id: 'theme.choose',
      title: 'Cambiar tema…',
      category: 'Apariencia',
      icon: 'palette',
      keywords: ['tema', 'theme', 'colores'],
      order: 90,
      run: () => app.chooseTheme(),
    },
    {
      id: 'theme.toggle',
      title: 'Alternar entre claro y oscuro',
      category: 'Apariencia',
      icon: 'sun',
      keywords: ['claro', 'oscuro'],
      order: 91,
      run: () => app.toggleTheme(),
    },
    {
      id: 'appearance.animations',
      title: 'Alternar animaciones',
      category: 'Apariencia',
      order: 92,
      run: () => app.toggleSetting('appearance.animations'),
    },

    /* -------------------------------- Sistema ----------------------------- */
    {
      id: 'system.reload',
      title: 'Recargar la interfaz',
      category: 'Sistema',
      icon: 'refresh',
      keywords: ['recargar', 'reload'],
      order: 100,
      run: () => app.reload(),
    },
    {
      id: 'system.capabilities',
      title: 'Volver a comprobar capacidades',
      category: 'Sistema',
      icon: 'shield',
      order: 101,
      run: () => app.recheckCapabilities(),
    },
    {
      id: 'system.diagnostics',
      title: 'Descargar el informe de diagnóstico',
      category: 'Sistema',
      icon: 'bug',
      order: 102,
      run: () => app.downloadDiagnostics(),
    },
    {
      id: 'system.exportSettings',
      title: 'Exportar la configuración',
      category: 'Sistema',
      icon: 'export',
      order: 103,
      run: () => app.exportSettings(),
    },
    {
      id: 'system.importSettings',
      title: 'Importar la configuración…',
      category: 'Sistema',
      icon: 'import',
      order: 104,
      run: () => app.importSettings(),
    },
    {
      id: 'system.resetSettings',
      title: 'Restaurar la configuración por defecto',
      category: 'Sistema',
      icon: 'undo',
      order: 105,
      dangerous: true,
      run: () => app.resetSettings(),
    },
    {
      id: 'system.syncScripts',
      title: 'Reconciliar scripts con el disco',
      category: 'Sistema',
      icon: 'refresh',
      order: 106,
      run: () => app.syncScripts(),
    },
    {
      id: 'system.openDataFolder',
      title: 'Mostrar la carpeta de datos',
      category: 'Sistema',
      icon: 'folder',
      order: 107,
      run: () => app.showDataFolder(),
    },
  ];

  /*
   * Alias internos que usa `ShortcutManager` (KEYMAP_PRESETS) para los atajos por defecto.
   * Se registran como comandos ocultos —no aparecen en la paleta— para que cada atajo tenga una
   * implementación real y no exista ningún camino muerto. La acción es exactamente la misma que la
   * del comando visible equivalente.
   */
  const aliases = [
    { id: 'runtime.format', title: 'Formatear documento', run: () => app.formatDocument() },
    { id: 'app.commandPalette', title: 'Abrir la paleta de comandos', run: () => app.palette?.show() },
    { id: 'app.toggleSidebar', title: 'Alternar la barra lateral', run: () => app.toggleSidebar() },
    { id: 'app.toggleTheme', title: 'Alternar el tema', run: () => app.toggleTheme() },
    { id: 'app.openSettings', title: 'Abrir los ajustes', run: () => app.openSettings() },
    { id: 'app.reloadInterface', title: 'Recargar la interfaz', run: () => app.reload() },
    { id: 'app.focusEditor', title: 'Enfocar el editor', run: () => { app.switchView('editor'); app.editor?.focus?.(); } },
    { id: 'app.focusConsole', title: 'Enfocar la consola', run: () => app.switchView('console') },
    { id: 'app.focusScripts', title: 'Enfocar los scripts', run: () => app.switchView('scripts') },
    { id: 'app.focusDashboard', title: 'Enfocar el panel', run: () => app.switchView('dashboard') },
    { id: 'view.zoomIn', title: 'Aumentar el tamaño del texto', run: () => app.editor?.zoomIn() },
    { id: 'view.zoomOut', title: 'Reducir el tamaño del texto', run: () => app.editor?.zoomOut() },
    { id: 'view.zoomReset', title: 'Restablecer el tamaño del texto', run: () => app.editor?.zoomReset() },
  ].map((definition) => ({ category: 'Atajos', hidden: true, keywords: ['atajo'], ...definition }));

  definitions.push(...aliases);

  const result = commands.registerMany(definitions);
  return { registered: result.registered, errors: result.errors, ids: definitions.map((definition) => definition.id) };
}
