import { useState, type FormEvent } from 'react';
import { ArrowUpRight, Blocks, Bot, Check, Code2, Copy, FileSearch, Gamepad2, Globe2, Image, Pencil, Plus, Shield, Sparkles, Trash2, Workflow } from 'lucide-react';
import type { Agent, Model, Mode, Provider } from '../types';
import { api } from '../api';
import { EmptyState, ErrorBanner, Modal, ProviderIcon } from './common';

const iconMap: Record<string, typeof Bot> = { sparkles: Sparkles, code: Code2, globe: Globe2, gamepad: Gamepad2, blocks: Blocks, 'file-search': FileSearch, workflow: Workflow, image: Image, audio: Sparkles, bot: Bot, pen: Pencil };
const modeOptions: Mode[] = ['LOW', 'MEDIO', 'ALTO', 'EXTRA', 'MAX'];
type AgentForm = { id?: string; name: string; description: string; icon: string; instructions: string; providerId: string; modelId: string; mode: Mode; tools: string[]; limits: { maxActions: number; timeoutSeconds: number; fileAccess: boolean; imageAccess: boolean; audioAccess: boolean; memoryEnabled: boolean } };
const blank: AgentForm = { name: '', description: '', icon: 'sparkles', instructions: 'Ayuda al usuario con rigor. Si tienes herramientas autorizadas, úsalas para completar acciones reales y comunica con precisión lo que has podido hacer.', providerId: '', modelId: '', mode: 'MEDIO', tools: [], limits: { maxActions: 8, timeoutSeconds: 120, fileAccess: false, imageAccess: false, audioAccess: false, memoryEnabled: false } };

export function AgentsPage({ agents, providers, modelsByProvider, selectedAgentId, onAgentChange, onRefresh, onGoChat, activeProjectId }: {
  agents: Agent[]; providers: Provider[]; modelsByProvider: Record<string, Model[]>; selectedAgentId: string; onAgentChange: (id: string) => void; onRefresh: () => void; onGoChat: () => void; activeProjectId: string | null;
}) {
  const [form, setForm] = useState<AgentForm | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const customAgents = agents.filter((agent) => !agent.builtin);
  const editAgent = (agent?: Agent) => setForm(agent ? { id: agent.id, name: agent.name, description: agent.description, icon: agent.icon, instructions: agent.instructions,
    providerId: agent.providerId || '', modelId: agent.modelId || '', mode: agent.mode, tools: [...agent.tools], limits: { maxActions: 8, timeoutSeconds: 120, fileAccess: Boolean(agent.limits.fileAccess), imageAccess: Boolean(agent.limits.imageAccess), audioAccess: Boolean(agent.limits.audioAccess), memoryEnabled: Boolean(agent.limits.memoryEnabled), ...agent.limits } } : { ...blank, limits: { ...blank.limits }, tools: [] });
  const save = async (event: FormEvent) => {
    event.preventDefault(); if (!form) return;
    setBusy(true); setError('');
    try {
      const payload = { name: form.name, description: form.description, icon: form.icon, instructions: form.instructions, providerId: form.providerId || null, modelId: form.modelId || null, mode: form.mode, tools: form.tools, limits: form.limits };
      await api(`/agents${form.id ? `/${encodeURIComponent(form.id)}` : ''}`, { method: form.id ? 'PATCH' : 'POST', body: JSON.stringify(payload) });
      setForm(null); setNotice(form.id ? 'Agente actualizado.' : 'Agente creado.'); onRefresh();
    } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar el agente.'); }
    finally { setBusy(false); }
  };
  const duplicate = async (agent: Agent) => { try { await api(`/agents/${encodeURIComponent(agent.id)}/duplicate`, { method: 'POST', body: '{}' }); onRefresh(); setNotice(`Se creó una copia de ${agent.name}.`); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo duplicar.'); } };
  const remove = async (agent: Agent) => { if (!window.confirm(`¿Eliminar el agente ${agent.name}?`)) return; try { await api(`/agents/${encodeURIComponent(agent.id)}`, { method: 'DELETE', body: JSON.stringify({ confirm: true }) }); if (selectedAgentId === agent.id) onAgentChange(''); onRefresh(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo eliminar.'); } };
  const useAgent = (agent: Agent) => { onAgentChange(agent.id); onGoChat(); };
  const selectedModelList = form?.providerId ? modelsByProvider[form.providerId] || [] : [];
  return <div className="page-content agents-page">
    <div className="page-heading-row"><div><div className="eyebrow"><span className="eyebrow-dot" /> EQUIPO DE TRABAJO</div><h1>Agentes</h1><p>Perfiles especializados que combinan instrucciones, modelo y permisos de herramientas.</p></div><button className="button button-primary" onClick={() => editAgent()}><Plus size={16} />Crear agente</button></div>
    {error && <ErrorBanner message={error} onDismiss={() => setError('')} />}{notice && <div className="success-banner"><Check size={15} />{notice}<button className="icon-button" onClick={() => setNotice('')}>×</button></div>}
    <div className="agent-access-banner"><div className="agent-access-icon"><Shield size={18} /></div><div><b>Permisos explícitos, acciones reales</b><p>Los agentes solo pueden leer o escribir dentro del proyecto seleccionado. El uso de herramientas necesita un modelo compatible configurado manualmente.</p></div><span>{activeProjectId ? 'PROYECTO SELECCIONADO' : 'SELECCIONA UN PROYECTO PARA USAR ARCHIVOS'}</span></div>
    {customAgents.length > 0 && <><div className="section-title-row"><div><span className="section-kicker">PERSONALIZADOS</span><h2>Mis agentes</h2></div><span className="section-count">{customAgents.length}</span></div><div className="agent-grid">{customAgents.map((agent) => <AgentCard key={agent.id} agent={agent} active={selectedAgentId === agent.id} onUse={useAgent} onEdit={() => editAgent(agent)} onDuplicate={() => void duplicate(agent)} onDelete={() => void remove(agent)} />)}</div></>}
    <div className="section-title-row builtin-title"><div><span className="section-kicker">LISTOS PARA USAR</span><h2>Agentes de Nexus</h2></div><span className="built-in-badge">PLANTILLAS</span></div>
    <div className="agent-grid builtin-grid">{agents.filter((agent) => agent.builtin).map((agent) => <AgentCard key={agent.id} agent={agent} active={selectedAgentId === agent.id} onUse={useAgent} onEdit={() => editAgent(agent)} onDuplicate={() => void duplicate(agent)} onDelete={() => void remove(agent)} />)}</div>
    {agents.length === 0 && <EmptyState icon={<Bot size={23} />} title="Preparando tus agentes" description="Recarga la página para sincronizar las plantillas de agentes." />}
    {form && <Modal wide title={form.id ? 'Configurar agente' : 'Crear agente'} description="Define el comportamiento y limita sus permisos. Un agente no puede ejecutar herramientas no declaradas." onClose={() => setForm(null)}>
      <form className="form-stack agent-form" onSubmit={save}>
        <div className="two-field-row"><label>Nombre<input required minLength={2} maxLength={80} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="p. ej. Revisor de código" /></label><label>Icono<select value={form.icon} onChange={(e) => setForm({ ...form, icon: e.target.value })}>{Object.keys(iconMap).map((icon) => <option key={icon} value={icon}>{icon}</option>)}</select></label></div>
        <label>Descripción<input maxLength={240} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Para qué sirve este agente" /></label>
        <label>Instrucciones de sistema<textarea required minLength={5} maxLength={8000} rows={6} value={form.instructions} onChange={(e) => setForm({ ...form, instructions: e.target.value })} placeholder="Define el rol, los objetivos, el estilo y los límites…" /></label>
        <div className="two-field-row"><label>Proveedor predeterminado<select value={form.providerId} onChange={(e) => setForm({ ...form, providerId: e.target.value, modelId: '' })}><option value="">Usar modelo del chat</option>{providers.map((provider) => <option value={provider.id} key={provider.id}>{provider.name}</option>)}</select></label><label>Modelo predeterminado<select value={form.modelId} disabled={!form.providerId} onChange={(e) => setForm({ ...form, modelId: e.target.value })}><option value="">Usar modelo del chat</option>{selectedModelList.map((model) => <option value={model.id} key={model.id}>{model.displayName} · {model.source}</option>)}</select></label></div>
        <label>Modo predeterminado<select value={form.mode} onChange={(e) => setForm({ ...form, mode: e.target.value as Mode })}>{modeOptions.map((mode) => <option key={mode} value={mode}>{mode}</option>)}</select></label>
        <div className="permission-box"><div className="permission-heading"><b>Herramientas autorizadas</b><small>Disponibles únicamente con un modelo configurado para herramientas.</small></div><div className="permission-options"><label><input type="checkbox" checked={form.tools.includes('read_files')} onChange={(e) => setForm({ ...form, tools: e.target.checked ? [...new Set([...form.tools, 'read_files'])] : form.tools.filter((t) => t !== 'read_files'), limits: { ...form.limits, fileAccess: e.target.checked || form.tools.includes('write_files') } })} />Leer lista y contenido de archivos</label><label><input type="checkbox" checked={form.tools.includes('write_files')} onChange={(e) => setForm({ ...form, tools: e.target.checked ? [...new Set([...form.tools, 'write_files'])] : form.tools.filter((t) => t !== 'write_files'), limits: { ...form.limits, fileAccess: e.target.checked || form.tools.includes('read_files') } })} />Crear o reemplazar archivos</label><label><input type="checkbox" checked={form.limits.imageAccess} onChange={(e) => setForm({ ...form, limits: { ...form.limits, imageAccess: e.target.checked } })} />Permitir imágenes adjuntas</label><label><input type="checkbox" checked={form.limits.audioAccess} onChange={(e) => setForm({ ...form, limits: { ...form.limits, audioAccess: e.target.checked } })} />Permitir entrada de voz transcrita</label><label><input type="checkbox" checked={form.limits.memoryEnabled} onChange={(e) => setForm({ ...form, limits: { ...form.limits, memoryEnabled: e.target.checked } })} />Memoria opcional (no activa hasta conectar una fuente)</label></div></div>
        <div className="two-field-row"><label>Acciones máximas<input type="number" min={1} max={8} value={form.limits.maxActions} onChange={(e) => setForm({ ...form, limits: { ...form.limits, maxActions: Number(e.target.value) } })} /></label><label>Tiempo límite (segundos)<input type="number" min={15} max={300} value={form.limits.timeoutSeconds} onChange={(e) => setForm({ ...form, limits: { ...form.limits, timeoutSeconds: Number(e.target.value) } })} /></label></div>
        <div className="agent-form-note"><Shield size={14} />La memoria persistente a largo plazo y las herramientas de imagen/audio de agente todavía no están conectadas. Los permisos se guardan, pero no habilitan funciones ausentes.</div>
        <div className="modal-actions"><button type="button" className="button button-quiet" onClick={() => setForm(null)}>Cancelar</button><button className="button button-primary" disabled={busy}>{busy ? 'Guardando…' : <>{form.id ? 'Guardar cambios' : 'Crear agente'} <ArrowUpRight size={15} /></>}</button></div>
      </form>
    </Modal>}
  </div>;
}

function AgentCard({ agent, active, onUse, onEdit, onDuplicate, onDelete }: { agent: Agent; active: boolean; onUse: (agent: Agent) => void; onEdit: () => void; onDuplicate: () => void; onDelete: () => void }) {
  const Icon = iconMap[agent.icon] || Bot;
  return <article className={`agent-card ${active ? 'agent-card-active' : ''}`}><div className="agent-card-top"><span className={`agent-icon agent-icon-${agent.icon}`}><Icon size={19} /></span><button className="icon-button" title="Duplicar agente" onClick={onDuplicate}><Copy size={14} /></button></div><div className="agent-card-content"><div className="agent-title-row"><h3>{agent.name}</h3>{agent.builtin && <span className="agent-template-tag">NEXUS</span>}</div><p>{agent.description || 'Agente personalizado para tus tareas.'}</p></div><div className="agent-tag-row"><span className="agent-mode-tag">{agent.mode}</span>{agent.tools.includes('read_files') && <span>LECTURA</span>}{agent.tools.includes('write_files') && <span>ESCRITURA</span>}{agent.providerId && <span className="agent-provider-tag"><ProviderIcon type="" size={11} />MODELO FIJO</span>}</div><div className="agent-card-footer"><button className={`button ${active ? 'button-secondary' : 'button-primary'} button-sm`} onClick={() => onUse(agent)}>{active ? <Check size={14} /> : <Sparkles size={14} />}{active ? 'Activo' : 'Usar agente'}</button><div><button className="icon-button" title="Editar agente" onClick={onEdit}><Pencil size={14} /></button><button className="icon-button danger-icon" title="Eliminar agente" onClick={onDelete}><Trash2 size={14} /></button></div></div></article>;
}
