import { useEffect, useState, type FormEvent } from 'react';
import { Check, CreditCard, KeyRound, Moon, ShieldCheck, Sun, UserRound, Volume2 } from 'lucide-react';
import type { Model, Mode, Provider, User } from '../types';
import { api } from '../api';
import { ErrorBanner, ProviderIcon } from './common';

type Usage = { credits: number; daily: { used: number; limit: number }; monthly: { used: number; limit: number }; adminBypass: boolean; history: any[] };
export function SettingsPage({ user, providers, modelsByProvider, mode, onModeChange, onUserUpdated, onThemeChanged }: { user: User; providers: Provider[]; modelsByProvider: Record<string, Model[]>; mode: Mode; onModeChange: (mode: Mode) => void; onUserUpdated: (user: User) => void; onThemeChanged: (theme: string) => void }) {
  const [name, setName] = useState(user.name);
  const [theme, setTheme] = useState(user.preferences?.theme || 'dark');
  const [defaultMode, setDefaultMode] = useState<Mode>(user.preferences?.defaultMode || 'MEDIO');
  const [defaultProviderId, setDefaultProviderId] = useState(user.preferences?.defaultProviderId || '');
  const [defaultModelId, setDefaultModelId] = useState(user.preferences?.defaultModelId || '');
  const [maxProviderId, setMaxProviderId] = useState(user.preferences?.preferredMaxProviderId || '');
  const [maxModelId, setMaxModelId] = useState(user.preferences?.preferredMaxModelId || '');
  const [voiceLanguage, setVoiceLanguage] = useState(user.preferences?.voiceLanguage || 'es-ES');
  const [usage, setUsage] = useState<Usage | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  useEffect(() => { void api<Usage>('/usage').then(setUsage).catch(() => null); }, []);
  useEffect(() => { setName(user.name); setTheme(user.preferences?.theme || 'dark'); setDefaultMode(user.preferences?.defaultMode || 'MEDIO'); setDefaultProviderId(user.preferences?.defaultProviderId || ''); setDefaultModelId(user.preferences?.defaultModelId || ''); setMaxProviderId(user.preferences?.preferredMaxProviderId || ''); setMaxModelId(user.preferences?.preferredMaxModelId || ''); setVoiceLanguage(user.preferences?.voiceLanguage || 'es-ES'); }, [user]);
  const availableModels = modelsByProvider[defaultProviderId] || [];
  const maxModels = modelsByProvider[maxProviderId] || [];
  const saveAccount = async (event: FormEvent) => {
    event.preventDefault(); setBusy(true); setError('');
    try { const result = await api<{ name: string }>('/profile/account', { method: 'PATCH', body: JSON.stringify({ name }) }); onUserUpdated({ ...user, name: result.name }); setNotice('Perfil actualizado.'); }
    catch (e) { setError(e instanceof Error ? e.message : 'No se pudo actualizar el perfil.'); }
    finally { setBusy(false); }
  };
  const savePreferences = async (event: FormEvent) => {
    event.preventDefault(); setBusy(true); setError('');
    try {
      const result = await api<{ preferences: Record<string, any> }>('/profile/preferences', { method: 'PATCH', body: JSON.stringify({ preferences: { theme, defaultMode, defaultProviderId: defaultProviderId || null, defaultModelId: defaultModelId || null, preferredMaxProviderId: maxProviderId || null, preferredMaxModelId: maxModelId || null, voiceLanguage } }) });
      onUserUpdated({ ...user, preferences: result.preferences }); onModeChange(defaultMode); onThemeChanged(theme); setNotice('Preferencias guardadas.');
    } catch (e) { setError(e instanceof Error ? e.message : 'No se pudieron guardar las preferencias.'); }
    finally { setBusy(false); }
  };
  const changeTheme = async (nextTheme: string) => { setTheme(nextTheme); onThemeChanged(nextTheme); try { const result = await api<{ preferences: Record<string, any> }>('/profile/preferences', { method: 'PATCH', body: JSON.stringify({ preferences: { theme: nextTheme } }) }); onUserUpdated({ ...user, preferences: result.preferences }); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar el tema.'); } };
  return <div className="page-content settings-page">
    <div className="page-heading-row"><div><div className="eyebrow"><span className="eyebrow-dot" /> CUENTA Y PREFERENCIAS</div><h1>Tu espacio</h1><p>Configura tu identidad, modelos predeterminados, modo de respuesta y uso.</p></div><div className="account-role-pill"><ShieldCheck size={14} />{user.role === 'admin' ? 'ADMINISTRADOR' : 'USUARIO'}</div></div>
    {error && <ErrorBanner message={error} onDismiss={() => setError('')} />}{notice && <div className="success-banner"><Check size={15} />{notice}<button className="icon-button" onClick={() => setNotice('')}>×</button></div>}
    <div className="settings-layout"><main className="settings-main">
      <section className="settings-card"><div className="settings-card-title"><span className="settings-card-icon"><UserRound size={17} /></span><div><h2>Perfil</h2><p>Tu cuenta privada de Nexus.</p></div></div><form className="settings-form" onSubmit={saveAccount}><div className="profile-identity"><span className="avatar avatar-profile">{user.name.slice(0, 1).toUpperCase()}</span><div><b>{user.email}</b><small>Miembro desde {new Date(user.createdAt).toLocaleDateString()}</small></div></div><label>Nombre visible<input value={name} maxLength={80} onChange={(e) => setName(e.target.value)} /></label><label>Correo electrónico<input value={user.email} disabled /><small className="field-help">El correo no se puede cambiar desde la interfaz.</small></label><button className="button button-secondary button-sm" disabled={busy}>Guardar perfil</button></form></section>
      <section className="settings-card"><div className="settings-card-title"><span className="settings-card-icon"><SettingsIcon /></span><div><h2>Preferencias</h2><p>Se sincronizan en esta cuenta.</p></div></div><form className="settings-form" onSubmit={savePreferences}><div className="setting-row"><div><b>Apariencia</b><small>Elige el tema del espacio de trabajo.</small></div><div className="theme-picker"><button type="button" className={theme === 'dark' ? 'selected' : ''} onClick={() => setTheme('dark')}><Moon size={15} />Oscuro</button><button type="button" className={theme === 'light' ? 'selected' : ''} onClick={() => setTheme('light')}><Sun size={15} />Claro</button></div></div>
        <label>Modo predeterminado<select value={defaultMode} onChange={(e) => setDefaultMode(e.target.value as Mode)}><option value="LOW">LOW · rápido y económico</option><option value="MEDIO">MEDIO · recomendado</option><option value="ALTO">ALTO · más profundidad</option><option value="EXTRA">EXTRA · análisis extenso</option><option value="MAX">MAX · mejor modelo disponible en tu cuenta</option></select></label>
        <div className="two-field-row"><label>Proveedor predeterminado<select value={defaultProviderId} onChange={(e) => { setDefaultProviderId(e.target.value); setDefaultModelId(''); }}><option value="">Elegir en cada chat</option>{providers.map((provider) => <option value={provider.id} key={provider.id}>{provider.name}</option>)}</select></label><label>Modelo predeterminado<select value={defaultModelId} disabled={!defaultProviderId} onChange={(e) => setDefaultModelId(e.target.value)}><option value="">Elegir en cada chat</option>{availableModels.map((model) => <option value={model.id} key={model.id}>{model.displayName}</option>)}</select></label></div>
        <div className="two-field-row"><label>Proveedor preferido para MAX<select value={maxProviderId} onChange={(e) => { setMaxProviderId(e.target.value); setMaxModelId(''); }}><option value="">Usar el modelo seleccionado</option>{providers.map((provider) => <option value={provider.id} key={provider.id}>{provider.name}</option>)}</select></label><label>Modelo preferido para MAX<select value={maxModelId} disabled={!maxProviderId} onChange={(e) => setMaxModelId(e.target.value)}><option value="">Usar el modelo seleccionado</option>{maxModels.map((model) => <option value={model.id} key={model.id}>{model.displayName}</option>)}</select></label></div><small className="field-help">MAX usa el modelo que selecciones aquí; si no se configura, mantiene el modelo del chat. Nexus no intenta adivinar cuál modelo es "el mejor".</small>
        <label>Idioma de voz<select value={voiceLanguage} onChange={(e) => setVoiceLanguage(e.target.value)}><option value="es-ES">Español · España</option><option value="es-MX">Español · México</option><option value="en-US">English · US</option><option value="en-GB">English · UK</option><option value="fr-FR">Français</option><option value="de-DE">Deutsch</option><option value="pt-BR">Português · Brasil</option></select></label>
        <div className="voice-info"><Volume2 size={15} /><span>La síntesis y el dictado se ejecutan mediante las funciones del navegador. El dictado puede procesarse externamente según el navegador; siempre requiere una acción explícita.</span></div><button className="button button-primary button-sm" disabled={busy}>Guardar preferencias</button></form></section>
      <section className="settings-card"><div className="settings-card-title"><span className="settings-card-icon"><CreditCard size={17} /></span><div><h2>Plan y créditos</h2><p>Los créditos son unidades internas, no dinero ni saldo del proveedor.</p></div></div><div className="plan-cards"><div className="plan-card-current"><span className="plan-card-label">PLAN ACTUAL</span><h3>FREE</h3><p>Cuotas configurables por el administrador.</p><div className="plan-meter"><i style={{ width: `${user.role === 'admin' ? 100 : Math.min(100, usage ? usage.monthly.used / Math.max(1, usage.monthly.limit) * 100 : 0)}%` }} /></div><small>{user.role === 'admin' ? 'Sin límites internos · aún aplican límites externos' : `${usage?.monthly.used?.toLocaleString() || '0'} / ${usage?.monthly.limit?.toLocaleString() || user.monthlyLimit.toLocaleString()} unidades este mes`}</small></div><div className="plan-card-future"><span>PRÓXIMAMENTE</span><h3>PRO</h3><p>Planes de pago todavía no implementados.</p></div><div className="plan-card-future"><span>PRÓXIMAMENTE</span><h3>MAX</h3><p>Sin cobros ni compras simuladas.</p></div></div><div className="credit-explainer"><KeyRound size={14} />Estimación interna por solicitud, reservada antes de ejecutarse y conciliada al finalizar. Las APIs externas facturan por separado según tu contrato.</div></section>
    </main>
    <aside className="settings-side"><div className="usage-card"><div className="usage-card-head"><span className="usage-icon"><ActivityIcon /></span><div><b>Consumo</b><small>{user.role === 'admin' ? 'Bypass interno activo' : 'Cuotas del plan FREE'}</small></div></div><div className="usage-big-number">{user.role === 'admin' ? '∞' : (usage?.credits ?? user.credits).toLocaleString()}<small>{user.role === 'admin' ? 'Administrador' : 'créditos restantes'}</small></div>{user.role !== 'admin' && <><div className="usage-limit-row"><span>Hoy</span><b>{usage?.daily.used?.toLocaleString() || 0}<small> / {usage?.daily.limit?.toLocaleString() || user.dailyLimit}</small></b></div><div className="usage-progress"><i style={{ width: `${usage ? Math.min(100, usage.daily.used / Math.max(1, usage.daily.limit) * 100) : 0}%` }} /></div><div className="usage-limit-row"><span>Este mes</span><b>{usage?.monthly.used?.toLocaleString() || 0}<small> / {usage?.monthly.limit?.toLocaleString() || user.monthlyLimit}</small></b></div><div className="usage-progress monthly"><i style={{ width: `${usage ? Math.min(100, usage.monthly.used / Math.max(1, usage.monthly.limit) * 100) : 0}%` }} /></div></>}<div className="usage-disclaimer">Las estimaciones no representan el coste de tu cuenta de proveedor. El administrador no tiene cuotas internas.</div></div>
      <div className="privacy-card"><ShieldCheck size={17} /><b>Control de privacidad</b><p>Conversaciones, claves y proyectos se aíslan por cuenta. Solo el texto que envías se comparte con el proveedor elegido.</p><div><span>01</span><small>Claves cifradas en almacenamiento local.</small></div><div><span>02</span><small>Sesiones seguras y protección CSRF.</small></div></div>
    </aside></div>
  </div>;
}
function SettingsIcon() { return <KeyRound size={17} />; }
function ActivityIcon() { return <CreditCard size={16} />; }
